<div class="block block-layered-nav">
	<div class="block-content">

	<?php foreach ($this->getStoreCategories() as $_category): ?>
		<?php if ($_category->getIsActive()): ?>
			<?php $isactive		= $this->isCategoryActive($_category); ?>
			<?php $hasChildren	= $_category->hasChildren(); ?>

			<?php if($isactive && $hasChildren): ?>

				<ul class="subcategory_<?php echo $_category->getId();?> subcategory">
					<?php foreach (Mage::getModel('catalog/category')->load($_category->getId())->getChildrenCategories() as $childCategory):?>

						<?php $isactive			= $this->isCategoryActive($childCategory); ?>
						<?php $hasmoreChildren	= $childCategory->hasChildren(); ?>
						<li class="category <?php echo $isactive ? 'active' : ''; ?>" lang="<?php echo $childCategory->getId(); ?>">
							<a href="<?php echo $childCategory->getUrl($_childCategory); ?>" ><?php echo $childCategory->getName(); ?></a>
						</li>

						<?php if($hasmoreChildren): ?>
						<li>								
							<ul class="subcategory_<?php echo $childCategory->getId(); ?> subcategory" style="display:<?php echo $isactive? 'block' : 'none'; ?>;">
								<?php foreach (Mage::getModel('catalog/category')->load($childCategory->getId())->getChildrenCategories() as $_childCategory):?>
									<?php $isactive	= $this->isCategoryActive($_childCategory);?>
									<li class="category">
										<a href="<?php echo $_childCategory->getUrl(); ?>"><?php echo $_childCategory->getName(); ?></a>
									</li>
								<?php endforeach; ?>
							</ul>
						</li>
						<?php endif ?>

					<?php endforeach;?>
				</ul>

			<?php endif ?>

		<?php endif ?>
	<?php endforeach ?>

	</div>
</div>

<script type="text/javascript">
/* jQuery.noConflict();
jQuery(document).ready(function(){	

	// Custom Menu
	jQuery(".category").click(function() {
		var open = this.getAttributeNode('lang').value;
		jQuery(".subcategory_" + open).slideToggle('medium');
	});	
	
}); */
</script>