<?php if($this->getCollection()->getSize()): ?>

<div class="amount">
	<?php echo ($this->getLastPageNum() > 1) ? $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) : $this->__('%s Item(s)', $this->getTotalNum()) ?>
</div>

<div class="limiter">
	<label for="limit_per_page">Display:</label>
	<select name="limit_per_page" onchange="setLocation(this.value)">
	<?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
		<option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>><?php echo $_limit ?></option>
	<?php endforeach; ?>
	</select>
</div>

<?php echo $this->getPagerHtml() ?>

<?php if( $this->isExpanded() ): ?>
<div class="sorter">

		<label for="sort_by">Sort By:</label>
		<select name="sort_by" onchange="setLocation(this.value)">
		<?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
			<option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>><?php echo $this->__($_order) ?></option>
		<?php endforeach; ?>
		</select>
		
		<?php if($this->getCurrentDirection() == 'desc'): ?>
			<a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>" class="arrow asc">Ascending</a>
		<?php else: ?>
			<a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>" class="arrow desc">Descending</a>
		<?php endif; ?>
</div>
<?php endif; ?>

<?php endif ?>


<?php //if($this->getCurrentDirection() == 'desc') : ?>
    <?php //$this->addOrderToAvailableOrders('created_at','Newest') ?>
<?php //else : ?>
    <?php //$this->addOrderToAvailableOrders('created_at','Oldest') ?>
<?php //endif; ?>
