<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>


<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>

<div class="hero_image no_image">
    <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</div>

<?php else: ?>

<div class="hero_image">
    <?php
		// $this->helper('catalog/image')->init($_product, 'image')
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(400,600).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>



<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more_images">
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(100,150); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
