<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products in Limited Rack. Please check back soon!') ?></p>
<?php else: ?>
<div class="category-products">

	<ul class="products-grid limited-rack cf">

    <?php $_collectionSize = $_productCollection->count() ?>

    <?php foreach ($_productCollection as $_product): ?>

            <?php $qty = ''; ?>

            <li class="item">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300,450); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>

                <span class="qty"><?php foreach ($_product->getTypeInstance()->getUsedProducts() as $childProduct) {   
                        // Get the inventory data for this child / Simple Product
                        $stockItem = Mage::getModel('cataloginventory/stock_item')->loadByProduct($childProduct);
                        $qty = (int)$stockItem->getQty();
                        echo $qty . " left";
                    } ?></span>

                <?php echo $this->getPriceHtml($_product, true) ?>
				
				<?php if(!$_product->isSaleable()): ?>
				<span class="availability out-of-stock"><?php echo $this->__('Out of stock') ?></span>
				<?php endif; ?>

            </li>

        <?php endforeach ?>

	</ul>
</div>
<?php endif; ?>
