<?php
    $_coreHelper = $this->helper('core');
    $_taxHelper  = $this->helper('tax');

    $_product = $this->getProduct();
    $_storeId = $_product->getStoreId();
    $_id = $_product->getId();
    $_simplePricesTax = ($_taxHelper->displayPriceIncludingTax() || $_taxHelper->displayBothPrices());
    $_minimalPriceValue = $_product->getMinimalPrice();
    $_minimalPrice = $_taxHelper->getPrice($_product, $_minimalPriceValue, $_simplePricesTax);
?>

<?php if (!$_product->isGrouped()): ?>

<div class="price_box">

    <?php $_price = $_taxHelper->getPrice($_product, $_product->getPrice()) ?>
    <?php $_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice(), $_simplePricesTax) ?>
    <?php $_finalPrice = $_taxHelper->getPrice($_product, $_product->getFinalPrice()) ?>
	
    <?php if ($_finalPrice >= $_price): ?>


			<?php if ($_finalPrice == $_price): ?>
				<?php echo $_coreHelper->currency($_price, true, true) ?>
			<?php else: ?>
				<?php echo $_coreHelper->currency($_finalPrice, true, true) ?>
			<?php endif; ?>


    <?php else: /* if ($_finalPrice == $_price): */ ?>

		<span class="price regular"><?php echo $_coreHelper->currency($_regularPrice, true, false) ?></span>
		<span class="price special"><?php echo $_coreHelper->currency($_finalPrice, true, false) ?></span>

    <?php endif; /* if ($_finalPrice == $_price): */ ?>

</div>
<?php endif; ?>
