<?php  
    $_helper = $this->helper('catalog/output');  
    $_product = $this->getProduct();
?>  

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
<div class="product">
	<div class="hide">  
		<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />  
		<input type="hidden" name="related_product" id="related-products-field" value="" />  
	</div>


	<div class="info">
		<div class="infomessage-product"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
	
		<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
		 
		<div class="details">  
			<?php echo $this->getChildHtml('prices') ?> 
			<?php echo $this->getChildHtml('product_type_data') ?>  
		</div>

		<div class="options">
			<?php echo $this->getChildHtml('product_options_wrapper') ?>
			<?php echo $this->getChildHtml('addtocart') ?>
		</div>
		
		<div class="description">
			<?php if ($_product->getShortDescription()):?>  
			<h2><?php echo $this->__('Overview') ?></h2>  
			<div class="short_description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>  
			<?php endif;?>  
			
			<?php echo $this->getChildHtml('description') ?>
		</div>
	</div>


	<div class="gallery"><?php echo $this->getChildHtml('media') ?></div> 
	
	
	<div class="related">
		<?php echo $this->getChildHtml('related') ?>
	</div>

</div>
</form>  