<?php
$catalogSearchHelper =  $this->helper('catalogsearch');
?>
<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
	<label for="search"><?php echo $this->__('Search:') ?></label>
	<input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" />
	<button title="<?php echo $this->__('Search') ?>" class="button btn-cart"><?php echo $this->__('Search') ?></button>
</form>