<span class="copyright right">
	<a href="/about">About Us</a> | <a href="/contact">Contact Us</a> | <a href="/customer-service">Customer Service</a> | <a href="/privacy">Privacy</a> | Salsit.com &copy; <?php echo date("Y") ?>
</span>

<ul class="social left">
	<li id="facebook"><a href="http://www.facebook.com/salsitstore" target="_blank">Facebook</a></li>
	<li id="twitter"><a href="https://twitter.com/SALSITSTORE" target="_blank">Twitter</a></li>
	<li id="instagram"><a href="http://instagram.com/salsitdotcom" target="_blank">Instagram</a></li>
	<li id="pinterest"><a href="http://pinterest.com/salsitstore/" target="_blank">Pinterest</a></li>
</ul>
