<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>
<?php if($this->getCollection()->getSize()): ?>

    <?php if($this->getShowAmounts()): ?>
	<div class="amount">
		<?php echo ($this->getLastPageNum() > 1) ? $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) : $this->__('%s Item(s)', $this->getTotalNum()) ?>
	</div>
    <?php endif ?>
	

    <?php if($this->getShowPerPage()): ?>
	<div class="limiter">
		<label for="limit_per_page">Display:</label>
		<select name="limit_per_page" onchange="setLocation(this.value)">
		<?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
			<option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
				<?php echo $_limit ?>
			</option>
		<?php endforeach; ?>
		</select>
	</div>
    <?php endif ?>

    <?php if($this->getLastPageNum()>1): ?>
    <div class="pager">
        <span>Page:</span>
        <ol>
        <?php if (!$this->isFirstPage()): ?>
            <li><a class="previous" href="<?php echo $this->getPreviousPageUrl() ?>">Previous</a></li>
        <?php endif;?>

        <?php if ($this->canShowFirst()): ?>
            <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
        <?php endif;?>

        <?php if ($this->canShowPreviousJump()): ?>
            <li><a class="previous_jump" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php foreach ($this->getFramePages() as $_page): ?>
            <?php if ($this->isPageCurrent($_page)): ?>
                <li class="current"><?php echo $_page ?></li>
            <?php else: ?>
                <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
            <?php endif;?>
        <?php endforeach;?>


        <?php if ($this->canShowNextJump()): ?>
            <li><a class="next_jump" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php if ($this->canShowLast()): ?>
          <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
        <?php endif;?>

        <?php if (!$this->isLastPage()): ?>
            <li>
                <a class="next" href="<?php echo $this->getNextPageUrl() ?>">Next</a>
            </li>
        <?php endif;?>
        </ol>

    </div>
    <?php endif; ?>

<?php endif ?>
